### ISSUE TITLE
Does not live reload on CSS change while using incremental

### ISSUE THREAD

**Issue by begincalendar** [RobertDeRose/jekyll-livereload#22]
Same issue as awood/hawkins#11.

**Comment by RobertDeRose** [comment]
I've had others open issues like this one, no one has been able to give me reproduction steps that actually cause issues like this for me, therefore I cannot fix the issue.

If you can provide me with details, such as; OS, version of Ruby, and a copy of your Gemfile.

If you're jekyll project is open source, a link to run that locally would be helpful as well.

**Comment by begincalendar** [comment]
## Environment

* OS: **Ubuntu 16.04**
* Ruby version: **2.5.0p0**

## Steps To Reproduce

1. Clone the repo at: https://github.com/begincalendar/live-reload-incremental-bug
2. `jekyll serve --livereload`
3. Change the color of the `h1` rule in `style.css` and you should get no automatic live reload in your browser.
4. Kill the Jekyll server
5. Remove the `incremental` setting from `_config.yml` (or set it to `false`)
6. Repeat steps 2-3 and you should get automatic live reload

## Side Note

I thought I should also add that if you remove the front matter from `index.html`, automatic live reloading does not work at all, regardless of the `incremental` setting value. 
Is that expected?

**Comment by RobertDeRose** [comment]
@begincalendar Thank you for the repo to help me reproduce the issue.

I can confirm that using the `incremental` flag does not work with CSS. It does seem to work with the HTML just fine.

However, two things.  The [`incremental`](https://jekyllrb.com/docs/configuration/) flag is still listed as experimental and warns that it can break things. The second thing is, the purpose of incremental is defeated by using `--livereload`.

As for the issue with the front-matter, apparently, that's required by Jekyll from what I can tell. Without it, it appears Jeykll doesn't consider the page needing processing and therefore the resulting file does not go through the pipeline and therefore my plugin can't inject the required script.

So, I would say, just disable `incremental` it doesn't provide any benefits and its still considered experimental so I don't think I am going to take the effort to fix it.

Also, since livereload support is now being added to Jekyll mainline, the need for my plugins is going to go away.

Thanks for opening the issue, hope this helps.
